try windows on azure

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -11,10 +11,14 @@ pr:
 
 variables:
   package_name: cysgp4
-  is.tag: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}
-  do.dist: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}
+  # is.tag: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}
+  # do.dist: ${{ startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}
   # do.dist: ${{ false }}
-  # is.tag: true
+  is.tag: ${{ true }}
+  do.dist: ${{ true }}
+  is.linux: ${{ startsWith(variables['Agent.OS'], 'Linux') }}
+  is.macos: ${{ startsWith(variables['Agent.OS'], 'Darwin') }}
+  is.win: ${{ startsWith(variables['Agent.OS'], 'Windows') }}
 
 jobs:
 
@@ -32,11 +36,11 @@ jobs:
 
   strategy:
     matrix:
-      linux35:
-        imageName: 'ubuntu-16.04'
-        python.version: '3.5'
-        py_whl: 35
-        numpy.version: '1.13.1'
+      # linux35:
+      #   imageName: 'ubuntu-16.04'
+      #   python.version: '3.5'
+      #   py_whl: 35
+      #   numpy.version: '1.13.1'
       linux36:
         imageName: 'ubuntu-16.04'
         python.version: '3.6'
@@ -48,32 +52,36 @@ jobs:
         ${{ if eq(variables['is.tag'], false) }}:
           docs.target: 'latest'
         do.tarball: ${{ eq(variables['is.tag'], true) }}
-      linux37:
-        imageName: 'ubuntu-16.04'
-        python.version: '3.7'
-        py_whl: 37
-        numpy.version: '1.14.5'
-      linux38:
-        imageName: 'ubuntu-16.04'
-        python.version: '3.8'
-        py_whl: 38
-        numpy.version: '1.14.5'
-      mac35:
-        imageName: 'macos-10.13'
-        python.version: '3.5'
-        numpy.version: '1.13.1'
+      # linux37:
+      #   imageName: 'ubuntu-16.04'
+      #   python.version: '3.7'
+      #   py_whl: 37
+      #   numpy.version: '1.14.5'
+      # linux38:
+      #   imageName: 'ubuntu-16.04'
+      #   python.version: '3.8'
+      #   py_whl: 38
+      #   numpy.version: '1.14.5'
+      # mac35:
+      #   imageName: 'macos-10.13'
+      #   python.version: '3.5'
+      #   numpy.version: '1.13.1'
       mac36:
         imageName: 'macos-10.13'
         python.version: '3.6'
         numpy.version: '1.13.1'
-      mac37:
-        imageName: 'macos-10.13'
-        python.version: '3.7'
-        numpy.version: '1.14.5'
-      mac38:
-        imageName: 'macos-10.13'
-        python.version: '3.8'
-        numpy.version: '1.14.5'
+      # mac37:
+      #   imageName: 'macos-10.13'
+      #   python.version: '3.7'
+      #   numpy.version: '1.14.5'
+      # mac38:
+      #   imageName: 'macos-10.13'
+      #   python.version: '3.8'
+      #   numpy.version: '1.14.5'
+      win35:
+        imageName: 'vs2017-win2016'
+        python.version: '3.6'
+        numpy.version: '1.13.1'
 
   pool:
     vmImage: $(imageName)
@@ -81,113 +89,138 @@ jobs:
   steps:
 
   - bash: |
-      echo "Build.SourceBranch" $BUILD_SOURCEBRANCH
-      echo "is.tag" $IS_TAG
-      echo "do.docs" $DO_DOCS
-      echo "docs.target" $DOCS_TARGET
-      echo "do.dist" $DO_DIST
-      echo "python.version" $PYTHON_VERSION
-      echo "py_whl" $PY_WHL
-      echo "numpy.version" $NUMPY_VERSION
-      echo "imageName" $IMAGENAME
+      echo "##vso[task.prependpath]$CONDA/bin"
+      echo "##vso[task.setvariable variable=conda.activate]source activate"
+    displayName: Add conda to PATH, bash
+    # condition: not(eq(variables['is.win'], true))
+    condition: not(startsWith(variables['Agent.OS'], 'Windows'))
+
+  - powershell: |
+      Write-Host "##vso[task.prependpath]$env:CONDA\Scripts"
+      echo "##vso[task.setvariable variable=conda.activate]call activate"
+    displayName: Add conda to PATH, powershell
+    # condition: eq(variables['is.win'], true)
+    condition: startsWith(variables['Agent.OS'], 'Windows')
+
+  - script: |
+      echo "Build.SourceBranch" $(Build.SourceBranch)
+      echo "Agent.OS" $(Agent.OS) "/" ${{ variables['Agent.OS'] }}
+      echo "is.linux" $(is.linux) "/" ${{ variables['is.linux'] }}
+      echo "is.macos" $(is.macos) "/" ${{ variables['is.macos'] }}
+      echo "is.win" $(is.win) "/" ${{ variables['is.win'] }}
+      echo "conda.activate" $(conda.activate)
+      echo "is.tag" $(is.tag)
+      echo "do.docs" $(do.docs)
+      echo "docs.target" $(docs.target)
+      echo "do.dist" $(do.dist)
+      echo "python.version" $(python.version)
+      echo "py_whl" $(py_whl)
+      echo "numpy.version" $(numpy.version)
+      echo "imageName" $(imageName)
     displayName: Show Vars
 
-  - bash: echo "##vso[task.prependpath]$CONDA/bin"
-    displayName: Add conda to PATH
-
-  - bash: conda create --yes --quiet --name cysgp4-env -c conda-forge
+  - script: conda create --yes --quiet --name cysgp4-env -c conda-forge
     displayName: Create Anaconda environment
 
-  - bash: |
-      source activate cysgp4-env
-      conda install --yes --quiet --name cysgp4-env -c conda-forge python=$PYTHON_VERSION numpy==$NUMPY_VERSION setuptools_scm twine pytest sgp4 wheel
+  - script: |
+      $(conda.activate) cysgp4-env
+      conda install --yes --quiet -c conda-forge python=$(python.version) numpy==$(numpy.version) setuptools_scm twine pytest sgp4 wheel
     displayName: Install Anaconda packages
 
-  - bash: |
-      source activate cysgp4-env
-      conda install --yes --quiet --name cysgp4-env -c conda-forge clang_osx-64 clangxx_osx-64 llvm-openmp openmp
+  # need to fix cctools and ld64 to slightly older version, otherwise an
+  # error ("ld: library not found for -lSystem") occurs during build
+  - script: |
+      $(conda.activate) cysgp4-env
+      conda install --yes --quiet --name cysgp4-env -c conda-forge clang_osx-64 clangxx_osx-64 llvm-openmp openmp cctools==921 ld64==409.12
     displayName: Prepare clang
-    condition: and(succeeded(), startsWith(variables['imageName'], 'macos'))
+    # condition: and(succeeded(), eq(variables['is.macos'], true))
+    condition: and(succeeded(), startsWith(variables['Agent.OS'], 'Darwin'))
 
-  - bash: |
-      source activate cysgp4-env
+  - script: |
+      $(conda.activate) cysgp4-env
       pip install -e .
     displayName: Building
 
-  - bash: |
-      source activate cysgp4-env
+  - script: |
+      $(conda.activate) cysgp4-env
       pip install pytest-azurepipelines
       pytest cysgp4
     displayName: Testing
 
-  - bash: |
-      source activate cysgp4-env
-      conda install --yes --quiet --name cysgp4-env -c conda-forge astropy sphinx-astropy
-      sphinx-build docs docs/_build/html -W -b html
-    displayName: Make docs
-    condition: and(succeeded(), eq(variables['do.docs'], true))
+  # # - script: |
+  # #     ${{ variables['conda.activate'] }} cysgp4-env
+  # #     conda install --yes --quiet --name cysgp4-env -c conda-forge astropy sphinx-astropy
+  # #     sphinx-build docs docs/_build/html -W -b html
+  # #   displayName: Make docs
+  # #   condition: and(succeeded(), eq(variables['do.docs'], true))
 
-  - task: DownloadSecureFile@1
-    inputs:
-      secureFile: ghpages_deploy_key
-    displayName: 'Get the deploy key'
+  # # - task: DownloadSecureFile@1
+  # #   inputs:
+  # #     secureFile: ghpages_deploy_key
+  # #   displayName: 'Get the deploy key'
 
-  - bash: |
-      source activate cysgp4-env
-      mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
-      chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
-      ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
-      mkdir gh_pages && cd gh_pages
-      git init
-      git config --local user.name "Benjamin Winkel"
-      git config --local user.email "bwinkel@mpifr.de"
-      git remote add github git@github.com:bwinkel/cysgp4.git
-      git fetch github gh-pages
-      git checkout --track github/gh-pages
-      # mkdir -p ./$DOCS_TARGET
-      rsync -av ../docs/_build/html/ ${DOCS_TARGET}/
-      git add -A && git commit -m "Update docs  ***NO_CI***"
-      bash ../retry.sh git push github
-    displayName: Publish docs
-    condition: and(succeeded(), eq(variables['do.docs'], true))
+  # # - bash: |
+  # #     # ${{ variables['conda.activate'] }} cysgp4-env
+  # #     mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
+  # #     chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
+  # #     ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
+  # #     mkdir gh_pages && cd gh_pages
+  # #     git init
+  # #     git config --local user.name "Benjamin Winkel"
+  # #     git config --local user.email "bwinkel@mpifr.de"
+  # #     git remote add github git@github.com:bwinkel/cysgp4.git
+  # #     git fetch github gh-pages
+  # #     git checkout --track github/gh-pages
+  # #     # mkdir -p ./$DOCS_TARGET
+  # #     rsync -av ../docs/_build/html/ ${DOCS_TARGET}/
+  # #     git add -A && git commit -m "Update docs  ***NO_CI***"
+  # #     bash ../retry.sh git push github
+  # #   displayName: Publish docs
+  # #   condition: and(succeeded(), eq(variables['do.docs'], true))
 
-  - task: TwineAuthenticate@1
-    inputs:
-      pythonUploadServiceConnection: pypi
-    displayName: 'Twine Authenticate'
+  # - task: TwineAuthenticate@1
+  #   inputs:
+  #     pythonUploadServiceConnection: pypi
+  #   displayName: 'Twine Authenticate'
 
-  - script: |
-      docker run -e NPY_NUM_BUILD_JOBS=4 -e PLAT=$(plat) -e package_name=$(package_name) -e py_whl=$(py_whl) --rm -v `pwd`:/io $(image) /io/.ci/build-wheels.sh
-      ls -lh wheelhouse/
-      mkdir -p dist
-      cp wheelhouse/$(package_name)*.whl dist/.
-      ls dist
-    displayName: Build wheels
-    condition: and(succeeded(), eq(variables['do.dist'], true), startsWith(variables['imageName'], 'ubuntu'))
+  # - bash: |
+  #     docker run -e NPY_NUM_BUILD_JOBS=4 -e PLAT=$(plat) -e package_name=$(package_name) -e py_whl=$(py_whl) --rm -v `pwd`:/io $(image) /io/.ci/build-wheels.sh
+  #     ls -lh wheelhouse/
+  #     mkdir -p dist
+  #     cp wheelhouse/$(package_name)*.whl dist/.
+  #     ls dist
+  #   displayName: Build wheels
+  #   condition: and(succeeded(), eq(variables['do.dist'], true), startsWith(variables['imageName'], 'ubuntu'))
 
-  - bash: |
-      source activate cysgp4-env
-      python setup.py bdist_wheel
-    displayName: Build wheels
-    condition: and(succeeded(), eq(variables['do.dist'], true), startsWith(variables['imageName'], 'macos'))
+  # - script: |
+  #     ${{ variables['conda.activate'] }} cysgp4-env
+  #     python setup.py bdist_wheel
+  #   displayName: Build wheels
+  #   condition: and(succeeded(), eq(variables['do.dist'], true), not(startsWith(variables['imageName'], 'ubuntu')))
 
-  - bash: |
-      source activate cysgp4-env
-      python -m twine upload -r "pypi" --config-file $(PYPIRC_PATH) dist/*.whl
-    displayName: Upload wheels
-    condition: and(succeeded(), eq(variables['do.dist'], true))
+  # # - script: |
+  # #     ${{ variables['conda.activate'] }} cysgp4-env
+  # #     python -m twine upload -r "pypi" --config-file %PYPIRC_PATH% dist/*.whl
+  # #   displayName: Upload wheels
+  # #   condition: and(succeeded(), eq(variables['do.dist'], true), not(startsWith(variables['imageName'], 'vs2017')))
 
-  - bash: |
-      source activate cysgp4-env
-      # conda install --yes --quiet --name cysgp4-env -c conda-forge twine wheel
-      python setup.py sdist
-      python -m twine upload -r "pypi" --config-file $(PYPIRC_PATH) dist/*.tar.gz
-    displayName: Upload tarball
-    condition: and(succeeded(), eq(variables['do.tarball'], true))
+  # # - script: |
+  # #     ${{ variables['conda.activate'] }} cysgp4-env
+  # #     python -m twine upload -r "pypi" --config-file $(PYPIRC_PATH) dist/*.whl
+  # #   displayName: Upload wheels
+  # #   condition: and(succeeded(), eq(variables['do.dist'], true), startsWith(variables['imageName'], 'vs2017'))
 
-  - bash: rm ~/.ssh/id_rsa || true
-    displayName: 'Cleanup docs deploy key'
-    condition: and(always(), eq(variables['do.docs'], true))
+  # # - script: |
+  # #     ${{ variables['conda.activate'] }} cysgp4-env
+  # #     # conda install --yes --quiet --name cysgp4-env -c conda-forge twine wheel
+  # #     python setup.py sdist
+  # #     python -m twine upload -r "pypi" --config-file $(PYPIRC_PATH) dist/*.tar.gz
+  # #   displayName: Upload tarball
+  # #   condition: and(succeeded(), eq(variables['do.tarball'], true))
+
+  # # - script: rm ~/.ssh/id_rsa || true
+  # #   displayName: 'Cleanup docs deploy key'
+  # #   condition: and(always(), eq(variables['do.docs'], true))
 
 
 # - job:
